## NUMPY Package

Numpy --> Pandas, scipy, Matplotlib, scikit-learn, scikit-image

In [6]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [7]:
import numpy as np

# 1D, 2D, ndarray, vector, matrix

- ndarray --> N Dimensional Array that represent vector and matrix
- vector --> array with 1 column
- matrix --> array witn many columns

In [7]:
c = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(c) #<-- array 2 dimensi
print(c[0]) #<--array index ke-0

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[1 2 3 4]


In [9]:
d = [[1,2,3,4],[5,6,7,8],[9,10,11,12]] #<-- list
print(d)

[[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]]


## Array

- np.array()
- np.zeros() --> array dengan angka 0
- np.ones() --> array dengan angka 1
- np.empty()
- np.arange() --> array dengan angka 'start', 'stop', 'step'
- np.append() --> menambah data array
- np.sort() --> mengurutkan data array
- np.delete() --> menghapus sebagian atau data seluruh array
- ndarray.ndim() --> mengetahui jumlah dimensi dari array
- ndarray.shape() --> mengetahui struktur dimensi array
- ndarray.size() --> mengetahui jumlah total element
- reshape --> mengubah bentuk dimensi namun dengan jumlah element yang sama

np.zeros(5)

In [11]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [15]:
np.arange(8)

array([0, 1, 2, 3, 4, 5, 6, 7])

In [16]:
np.arange(1,10,3)

array([1, 4, 7])

In [24]:
a = np.zeros(2)
b = np.ones(3)

np.append(a,b)

array([0., 0., 1., 1., 1.])

In [26]:
np.delete(np.append(a, b), 1) #<-- index ke-1 dihapus

array([0., 1., 1., 1.])

In [27]:
c = np.array([1,2,3,4,5,7,9,8,10])
np.sort(c)

array([ 1,  2,  3,  4,  5,  7,  8,  9, 10])

In [29]:
array3d = np.array([
    [[1,2,1,2],[3,4,3,4]],
    [[5,6,7,8],[9,10,9,11]],
    [[9,0,3,5],[2,6,5,9]]
])

#level 1 ada 3 <-- ada 3 baris
#level 2 ada 2 <-- ada 2 list dalam setiap baris
#level 3 ada 4 <-- isi dari list

In [31]:
array3d.ndim

3

In [32]:
array3d.shape

(3, 2, 4)

In [33]:
array3d.size

24

# reshape

In [38]:
a = np.array([1,2,3,4,5,6])
a

array([1, 2, 3, 4, 5, 6])

In [39]:
a.reshape(6, 1)

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [40]:
a.reshape(2,3)

array([[1, 2, 3],
       [4, 5, 6]])

In [42]:
a.reshape(3,2)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [44]:
a.reshape(4,2) # <-- jika di total estimasi element adalah 8 dan bukan original 6

ValueError: cannot reshape array of size 6 into shape (4,2)

# menambah dimensi array 

- menggunakan np.newaxis
- menggunakan np.expand.dims

bedanya adalah axis mana yang akan ditambahkan dimensi baru
np.newaxis --> menambahkan disisi axis 0 (row)
np.expand_dims --> menambahkan disisi axis 1 (column)

In [49]:
a = np.arange(6)
a

array([0, 1, 2, 3, 4, 5])

In [51]:
a.ndim # <--- jumlah dimensi

1

In [57]:
b = a[np.newaxis, :]
b

array([[0, 1, 2, 3, 4, 5]])

In [65]:
b.ndim

2

In [66]:
b.shape

(1, 6)

In [68]:
b = a[:, np.newaxis]
b

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5]])

In [69]:
b.shape

(6, 1)

In [62]:
b = np.expand_dims(a, axis=0)
b

array([[0, 1, 2, 3, 4, 5]])

In [71]:
b.shape

(6, 1)

In [70]:
b = np.expand_dims(a, axis=1)
b

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5]])

In [63]:
b.shape

(1, 6)

## indexing & slicing

In [72]:
a = np.array([1,3,4,7,8,9,11,13])

In [83]:
print(a)
print(a[0])
print(a[2])
print(a[0:3])
print(a[2:6])
print(a[2:])
print(a[-3:])
print(a[:4])
print(a[:-5])

[ 1  3  4  7  8  9 11 13]
1
4
[1 3 4]
[4 7 8 9]
[ 4  7  8  9 11 13]
[ 9 11 13]
[1 3 4 7]
[1 3 4]


In [87]:
print(a[a>=5])
print(a[a<7])
print(a[a%2==0])
print(a[(a>=3)&(a<=11)])

[ 7  8  9 11 13]
[1 3 4]
[4 8]
[ 3  4  7  8  9 11]


# teknik lain membuat numpy array
- vstack ==> vrtical stack
- hstack ==> horizontal stack
- hsplit ==> horizontal split



In [9]:
arr1 = np.array([20,21,24,23,27,28])
arr2 = np.array([11,12,13,15,17,16])
c = np.vstack((arr1, arr2))
c

array([[20, 21, 24, 23, 27, 28],
       [11, 12, 13, 15, 17, 16]])

In [14]:
arr1 = np.stack([[1,2], [1,4], [2,7]])
arr2 = np.stack([[11,12], [13,15], [11,14]])
c = np.vstack((arr1, arr2))
c


array([[ 1,  2],
       [ 1,  4],
       [ 2,  7],
       [11, 12],
       [13, 15],
       [11, 14]])

In [15]:
d = np.vstack((arr2,arr1))
d

array([[11, 12],
       [13, 15],
       [11, 14],
       [ 1,  2],
       [ 1,  4],
       [ 2,  7]])

In [26]:
e = np.hstack((arr1,arr2))
e

array([[ 1,  2, 11, 12],
       [ 1,  4, 13, 15],
       [ 2,  7, 11, 14]])

In [19]:
f = np.hstack((arr2,arr1))
f

array([[11, 12,  1,  2],
       [13, 15,  1,  4],
       [11, 14,  2,  7]])

In [24]:
arr3 = np.array([[1,6,7]])

In [30]:
arr_hstck = np.hstack((arr2,arr3))
arr_hstck #<== list array 3 dan array 2 dimensinya tidak sama

ValueError: all the input array dimensions for the concatenation axis must match exactly, but along dimension 0, the array at index 0 has size 3 and the array at index 1 has size 1

In [33]:
arr_vstck = np.vstack((arr1, arr3))
arr_vstck #<== list array 3 dan array 2 dimensinya tidak sama

ValueError: all the input array dimensions for the concatenation axis must match exactly, but along dimension 1, the array at index 0 has size 2 and the array at index 1 has size 3

In [43]:
arr4 = np.array([[1,2,3,4,5,6,7,8],[11,12,14,15,17,18,20,21]])
arr4.size

16

In [45]:
hasil_split = np.hsplit(arr4,4) #ask kenapa kebanyakan selalu 2 dimensi sewaktu di split
hasil_split

[array([[ 1,  2],
        [11, 12]]),
 array([[ 3,  4],
        [14, 15]]),
 array([[ 5,  6],
        [17, 18]]),
 array([[ 7,  8],
        [20, 21]])]

In [46]:
hasil_split[0]

array([[ 1,  2],
       [11, 12]])

In [47]:
hasil_split[-2]

array([[ 5,  6],
       [17, 18]])

In [48]:
arr4 #<== array 4 yg lama tidak berubah

array([[ 1,  2,  3,  4,  5,  6,  7,  8],
       [11, 12, 14, 15, 17, 18, 20, 21]])

hasil_split2 = np.hsplit(arr4,3)
hasil_split2 #<== array tidak bisa dibagi menjadi bagian yang sama besar dimensinya

# view & copy

In [54]:
arr5 = arr4.view()
arr5

array([[ 1,  2,  3,  4,  5,  6,  7,  8],
       [11, 12, 14, 15, 17, 18, 20, 21]])

In [56]:
arr6 = arr3.copy()
arr6

array([[1, 6, 7]])

## array operation
- addition, subtraction, multiplication, division
- maximum, minimum, mean, sum, product, standard deviation


syaratnya adalah dimensi dan size nya sama

In [57]:
arr6 = np.array([[10,11,12,13,14,15,16],
                [20,21,22,23,24,25,26]
                ])
arr6

array([[10, 11, 12, 13, 14, 15, 16],
       [20, 21, 22, 23, 24, 25, 26]])

In [58]:
arr6 + 3 #semua element ditambah 3

array([[13, 14, 15, 16, 17, 18, 19],
       [23, 24, 25, 26, 27, 28, 29]])

In [59]:
arr6 * 2

array([[20, 22, 24, 26, 28, 30, 32],
       [40, 42, 44, 46, 48, 50, 52]])

In [60]:
arr6 / 2

array([[ 5. ,  5.5,  6. ,  6.5,  7. ,  7.5,  8. ],
       [10. , 10.5, 11. , 11.5, 12. , 12.5, 13. ]])

In [62]:
arr6 - 5

array([[ 5,  6,  7,  8,  9, 10, 11],
       [15, 16, 17, 18, 19, 20, 21]])

In [63]:
arr6

array([[10, 11, 12, 13, 14, 15, 16],
       [20, 21, 22, 23, 24, 25, 26]])

In [64]:
arr6.sum()

252

In [65]:
arr7 = np.array([[5,6,7,8],
                [10,12,13,14]
                ])

In [68]:
arr7.sum(axis=0)

array([15, 18, 20, 22])

In [69]:
arr7.sum(axis=1)

array([26, 49])

In [71]:
panjang = np.array([10,20,30,40,50,60])
lebar = np.array([5,10,15,20,25,30])
tinggi = np.array([10,20,15,30,45,60])

In [73]:
Luas = panjang * lebar
Luas

array([  50,  200,  450,  800, 1250, 1800])

In [74]:
volume = Luas * tinggi
volume

array([   500,   4000,   6750,  24000,  56250, 108000])

In [78]:
A = np.array([[1,3,4,7,9,10],[2,3,6,8,9,11],
              [1,4,6,10,12,14],[3,4,8,10,14,19]])

In [79]:
A.sum()

178

In [94]:
A.sum((0)) # <== sama dengan axis=0

array([ 7, 14, 24, 35, 44, 54])

In [81]:
A.sum(axis=0)

array([ 7, 14, 24, 35, 44, 54])

In [82]:
A.sum(axis=1)

array([34, 39, 47, 58])

In [96]:
A.sum((1)) # <== sama dengan axis=1

array([34, 39, 47, 58])

In [98]:
A.sum((2)) # <== karena bukan array > 2 dimensi

AxisError: axis 2 is out of bounds for array of dimension 2

In [99]:
A.min()

1

In [84]:
A.min(axis=1)

array([1, 2, 1, 3])

In [85]:
A.min(axis=0)

array([ 1,  3,  4,  7,  9, 10])

In [86]:
A.max()

19

In [88]:
A.min((0)) # <== sama dengan axis=0

array([ 1,  3,  4,  7,  9, 10])

In [100]:
A.min(axis=0)

array([ 1,  3,  4,  7,  9, 10])

In [101]:
A.std()

4.517712056143266

In [102]:
A.mean()

7.416666666666667

In [103]:
A.mean(axis=0)

array([ 1.75,  3.5 ,  6.  ,  8.75, 11.  , 13.5 ])

In [105]:
A.mean((1)) # <== sama dengan axis=1

array([5.66666667, 6.5       , 7.83333333, 9.66666667])

### MATRIX
- dot <--- product / perkalian antar matrix
- indexing
- aggregation

In [111]:
A = np.array([[1,3,4,7,9,10],[2,3,6,8,9,11],
              [1,4,6,10,12,14],[3,4,8,10,14,19]])

B = np.array ([[11,12,13,14],[20,21,22,24],
              [20,21,22,24],[30,33,34,35],
              [1,2,3,4],[8,9,10,11]])

In [107]:
print(A)

[[ 1  3  4  7  9 10]
 [ 2  3  6  8  9 11]
 [ 1  4  6 10 12 14]
 [ 3  4  8 10 14 19]]


In [108]:
print(A.shape)

(4, 6)


In [112]:
print(B)
print(B.shape)

[[11 12 13 14]
 [20 21 22 24]
 [20 21 22 24]
 [30 33 34 35]
 [ 1  2  3  4]
 [ 8  9 10 11]]
(6, 4)


In [113]:
np.dot(A,B)

array([[450, 498, 532, 573],
       [539, 594, 633, 681],
       [635, 702, 749, 806],
       [739, 817, 875, 945]])

In [158]:
C = np.array([[4,2],[1,2]])
D = np.array([[3,1],[2,5]])

In [159]:
print(C)
print(D)

[[4 2]
 [1 2]]
[[3 1]
 [2 5]]


In [156]:
print(C.shape)

(2, 2)


In [157]:
print(D.shape)

(2, 2)


In [174]:
np.dot(C,D)

# Cara :
# sumproduct dari baris ke-1 matrix C dengan kolom ke-1 matrix D
# sumproduct dari baris ke-2 matrix C dengan kolom ke-1 matrix D
# sumproduct dari baris ke-1 matrix C dengan kolom ke-2 matrix D
# sumproduct dari baris ke-2 matrix C dengan kolom ke-2 matrix D
# visualisasi dot product bisa dilihat di website ini https://www.mathsisfun.com/algebra/matrix-multiplying.html

array([[16, 14],
       [ 7, 11]])

In [168]:
E = np.array([[1,2,3],[4,2,5],[4,6,8]])
E

array([[1, 2, 3],
       [4, 2, 5],
       [4, 6, 8]])

In [167]:
F = np.array([[1,2,4],[4,5,2],[6,8,10]])
F

array([[ 1,  2,  4],
       [ 4,  5,  2],
       [ 6,  8, 10]])

In [171]:
E.shape

(3, 3)

In [172]:
F.shape

(3, 3)

In [173]:
np.dot(E,F)

array([[ 27,  36,  38],
       [ 42,  58,  70],
       [ 76, 102, 108]])

### Transpose & Reshape Matrix

In [178]:
A = np.array([[0,1,2],[3,4,5]])
A

array([[0, 1, 2],
       [3, 4, 5]])

In [179]:
A.shape

(2, 3)

In [177]:
A.T

array([[0, 3],
       [1, 4],
       [2, 5]])

In [180]:
A.T.shape

(3, 2)

In [182]:
A.reshape(3,2)

array([[0, 1],
       [2, 3],
       [4, 5]])

### Flatten N-Dimensional Array
- .flatten() ==> bikin array baru, 'deep'
- .ravel() ==> copy array induk, 'shallow'

In [183]:
A

array([[0, 1, 2],
       [3, 4, 5]])

In [184]:
A.flatten()

array([0, 1, 2, 3, 4, 5])

In [185]:
A.ravel()

array([0, 1, 2, 3, 4, 5])

In [187]:
B = np.array([[0,1,2,3],[3,4,5,6],[4,5,6,7]])
B

array([[0, 1, 2, 3],
       [3, 4, 5, 6],
       [4, 5, 6, 7]])

In [188]:
B.shape

(3, 4)

In [189]:
B.flatten()

array([0, 1, 2, 3, 3, 4, 5, 6, 4, 5, 6, 7])

In [190]:
B.ravel()

array([0, 1, 2, 3, 3, 4, 5, 6, 4, 5, 6, 7])